# Generated by Django 5.2.2 on 2025-06-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_users_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'User'},
        ),
    ]
